---
# This is a comment at the beginning of the playbook file
# It helps provide context or information about the playbook

# Define the name of the playbook
- name: Example Playbook
  # The 'hosts' section specifies the target hosts or groups of hosts
  hosts: web_servers
  # 'become' option is used to execute tasks with elevated privileges (sudo)
  become: yes
  # 'become_user' specifies the user to become when executing tasks
  become_user: root

  # Define variables that can be used throughout the playbook
vars:
  website_directory: /var/www/html/mywebsite
  local_html_file: /path/to/local/index.html
  list_example: [1,2,3,10]
  i_int: 12
  j_int: 13
  s_str: "AHOJ"
  
  # Define a list of tasks to be executed on the target hosts
  tasks:

# Task 0: Define a variable
    - name: Define a custom fact
      # Use the 'set_fact' module to define a variable named 'my_var'
      set_fact:
        my_var: "Hello, Ansible!"

#############################################################
    # Task 1: Ensure that the Apache web server is installed
    - name: Install Apache
      # 'apt' module is used for package management on Debian-based systems
      apt:
        name: apache2
        state: present
      # 'register' saves the task result to a variable for later use
      register: apache_installed

    # Task 2: Ensure Apache service is running and enabled
    - name: Start Apache and enable at boot
      # 'service' module is used to manage services
      service:
        name: apache2
        state: started
        enabled: yes
      # 'when' conditionally runs this task if Apache was installed in Task 1
      when: apache_installed.changed
#############################################################

    # Task 3: Create a website directory
    - name: Create web directory
      # 'file' module is used for file and directory operations
      file:
        path: /var/www/html/mywebsite
        state: directory
        mode: '0755'

    # Task 4: Copy a local HTML file to the web directory
    - name: Copy HTML file
      # 'copy' module is used to copy files from the controller to the target hosts
      copy:
        src: /path/to/local/index.html
        dest: /var/www/html/mywebsite/index.html

    # Task 5: Ensure the index.html file has the correct permissions
    - name: Set permissions on index.html
      file:
        path: /var/www/html/mywebsite/index.html
        mode: '0644'
        
##################################################################

    # Task 6: Configure the Apache virtual host
    - name: Configure Apache virtual host
      # 'template' module is used to create configuration files from templates
      template:
        src: templates/vhost.conf.j2
        dest: /etc/apache2/sites-available/mywebsite.conf
      # 'notify' triggers the 'Reload Apache' handler when this task changes
      notify: Reload Apache

  # Handlers are tasks that are only executed if notified by other tasks
  handlers:
    # Handler 1: Reload the Apache service
    - name: Reload Apache
      # 'service' module is used to reload the Apache service
      service:
        name: apache2
        state: reloaded

##################################################################
   
  # Task 7: Debug multiple variables
    - name: Debug multiple variables
      # Use the 'debug' module to display values of multiple variables
      debug:
        var: 
          - my_var
          - ansible_hostname  # Display the hostname of the target host
          - ansible_distribution  # Display the Linux distribution of the target host

    # Task 8: Debug with custom messages
    - name: Debug with custom messages
      # Use the 'debug' module to display custom messages along with variable values
      debug:
        msg: "The value of my_var is: {{ my_var }}"
